version: '3.8'

services:
  # Web App (Frontend)
  softmad.leadgeneration:
    image: ${DOCKER_REGISTRY-}softmadleadgeneration
    build:
      context: .
      dockerfile: Softmad.LeadGeneration/Dockerfile
    expose:
      - "80"  # Expose port 80 internally for network communication
    networks:
      - softmad-network  # Attach to the shared network
    depends_on:
      - softmad.services.leadgeneration  # Ensure API is running before web app

  # Dapr Sidecar for Web App
  softmad.leadgeneration-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "Softmad-LeadGeneration", "-app-port", "80" ]
    depends_on:
      - softmad.leadgeneration  # Ensure web app is running
    network_mode: "service:softmad.leadgeneration"  # Attach to same network as web app

  # Web API (Backend)
  softmad.services.leadgeneration:
    image: ${DOCKER_REGISTRY-}softmadservicesleadgeneration
    build:
      context: .
      dockerfile: Softmad.Services.LeadGeneration/Dockerfile
    expose:
      - "80"  # Expose port 80 internally for network communication
    networks:
      - softmad-network  # Attach to the shared network

  # Dapr Sidecar for Web API
  softmad.services.leadgeneration-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd", "-app-id", "Softmad-Services-LeadGeneration", "-app-port", "80" ]
    depends_on:
      - softmad.services.leadgeneration  # Ensure API is running
    network_mode: "service:softmad.services.leadgeneration"  # Attach to same network as API

# Create a shared network
networks:
  softmad-network:
    driver: bridge

  # local.sqlservercontainer:
  #   image: mcr.microsoft.com/mssql/server:2022-latest 
  #   hostname: 'sqlserver'
  #   environment:  
  #     ACCEPT_EULA: Y  
  #     SA_PASSWORD: "adminPassw0rd"  
  #   volumes:  
  #     - ./data/mssql:/var/opt/mssql3  
  #   ports:  
  #     - '1433:1433'  
  #   expose:  
  #     - 1433  
